/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaproject;

import com.sun.glass.events.KeyEvent;
import javax.swing.*;
import loginpanel.*;
import com.toedter.calendar.JCalendar;
import java.util.*;
import java.text.*;

/**
 *
 * @author amonkats
 */
public class LibraryForm2 extends javax.swing.JFrame {

    /**
     * Creates new form LibraryForm2
     */
    public LibraryForm2() {
        initComponents();
        setLocation(135,90);
        setResizable(false);
        setTitle("IUEA Database Oriented System");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bookId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        bookTitle = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        authorName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        publisher = new javax.swing.JTextField();
        edition = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        invoiceNo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        invoiceDate = new com.toedter.calendar.JDateChooser();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(996, 354));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Librarian's Panel");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 282, 27));

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel2.setText("Student's Books Entry Form");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 239, 23));

        jLabel3.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel3.setText("Book ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 80, -1));

        bookId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bookIdKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                bookIdKeyTyped(evt);
            }
        });
        jPanel1.add(bookId, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 130, 34));

        jLabel4.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel4.setText("Book Title");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 82, 20));

        bookTitle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bookTitleKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                bookTitleKeyTyped(evt);
            }
        });
        jPanel1.add(bookTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 130, 31));

        jLabel5.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel5.setText("Author Name");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, -1));

        authorName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                authorNameKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                authorNameKeyTyped(evt);
            }
        });
        jPanel1.add(authorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 130, 33));

        jLabel6.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel6.setText("Publisher");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 82, 30));

        publisher.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                publisherKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                publisherKeyTyped(evt);
            }
        });
        jPanel1.add(publisher, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 130, 32));

        edition.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                editionKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                editionKeyTyped(evt);
            }
        });
        jPanel1.add(edition, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 130, 34));

        jLabel8.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel8.setText("Invoice No.");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 215, 75, 20));

        invoiceNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                invoiceNoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                invoiceNoKeyTyped(evt);
            }
        });
        jPanel1.add(invoiceNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, 130, 31));

        jLabel9.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel9.setText("Invoice Date");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 263, -1, 20));

        jButton1.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jButton1.setText("Issue");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 310, 78, 37));

        jButton2.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, 91, 37));

        jLabel10.setFont(new java.awt.Font("Old English Text MT", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 51, 51));
        jLabel10.setText("International University Of East Africa");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 420, 20));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\amonkats\\Documents\\NetBeansProjects\\JavaProject\\src\\javaproject\\pics\\Logo_sized.png")); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 63, 52));

        jButton3.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 80, 40));

        jLabel12.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel12.setText("Edition");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 155, 75, 20));
        jPanel1.add(invoiceDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, 130, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       
        this.hide();
        new LibraryForm().setVisible(true);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        System.exit(0);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if(bookId.getText().length() == 0 && bookTitle.getText().length() == 0 && bookTitle.getText().length() == 0
           && authorName.getText().length() == 0 && publisher.getText().length() == 0 && edition.getText().length() == 0
           && invoiceNo.getText().length() == 0){
            
            JOptionPane.showMessageDialog(jPanel1, "Nothing to issue !", "Error !", JOptionPane.ERROR_MESSAGE);
            
        }
        
        else if(bookId.getText().length() == 0){
          JOptionPane.showMessageDialog(jPanel1, "Fill in Book ID !", "Error !", JOptionPane.ERROR_MESSAGE);
          bookId.requestFocus();
        }
        
         else if(bookTitle.getText().length() == 0){
          JOptionPane.showMessageDialog(jPanel1, "Fill in Book Title !", "Error !", JOptionPane.ERROR_MESSAGE);
          bookTitle.requestFocus();
        }
        
         else if(authorName.getText().length() == 0){
          JOptionPane.showMessageDialog(jPanel1, "Fill in Author Name !", "Error !", JOptionPane.ERROR_MESSAGE);
          authorName.requestFocus();
        }
        
         else if(publisher.getText().length() == 0){
          JOptionPane.showMessageDialog(jPanel1, "Fill in Publisher !", "Error !", JOptionPane.ERROR_MESSAGE);
          publisher.requestFocus();
        }
        
         else if(edition.getText().length() == 0){
          JOptionPane.showMessageDialog(jPanel1, "Fill in Edition !", "Error !", JOptionPane.ERROR_MESSAGE);
          edition.requestFocus();
        }
        
         else if(invoiceNo.getText().length() == 0){
          JOptionPane.showMessageDialog(jPanel1, "Fill in Invoice No !", "Error !", JOptionPane.ERROR_MESSAGE);
          invoiceNo.requestFocus();
        }
        
         else if(invoiceDate.getDate().equals(null)){
          JOptionPane.showMessageDialog(jPanel1, "Fill in Invoice Date !", "Error !", JOptionPane.ERROR_MESSAGE);
          invoiceDate.requestFocus();
        }
        
         else{
           JOptionPane.showMessageDialog(jPanel1, "WELCOME TO IUEA LIBRARY");  
           dispose();
           JLabel issueMessage = new JLabel("");
           String id = bookId.getText();
           String title = bookTitle.getText();
           String name = authorName.getText();
           String pub = publisher.getText();
           String ed = edition.getText();
           String num = invoiceNo.getText();
           SimpleDateFormat sdf = new SimpleDateFormat("MMM  dd,  yyyy");
           Date date = invoiceDate.getDate();
           String d = sdf.format(date);
           
           new LibraryForm3(issueMessage,id,title,name,pub,ed,num,d).setVisible(true);
         
         }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bookIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bookIdKeyTyped
       
        if(Character.isLetter(evt.getKeyChar()) && !(evt.getKeyChar() == KeyEvent.VK_ENTER)){
            JOptionPane.showMessageDialog(jPanel1, "Enter Digits only !","Error",JOptionPane.ERROR_MESSAGE);
            evt.consume();
        }
    }//GEN-LAST:event_bookIdKeyTyped

    private void bookTitleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bookTitleKeyTyped
        
        if(Character.isDigit(evt.getKeyChar()) && !(evt.getKeyChar() == KeyEvent.VK_ENTER)){
            JOptionPane.showMessageDialog(jPanel1, "Enter Characters only !","Error",JOptionPane.ERROR_MESSAGE);
            evt.consume();
        }
        
    }//GEN-LAST:event_bookTitleKeyTyped

    private void authorNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_authorNameKeyTyped
        
        if(Character.isDigit(evt.getKeyChar()) && !(evt.getKeyChar() == KeyEvent.VK_ENTER)){
            JOptionPane.showMessageDialog(jPanel1, "Enter Characters only !","Error",JOptionPane.ERROR_MESSAGE);
            evt.consume();
        }
    }//GEN-LAST:event_authorNameKeyTyped

    private void publisherKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_publisherKeyTyped
       
        if(Character.isDigit(evt.getKeyChar()) && !(evt.getKeyChar() == KeyEvent.VK_ENTER)){
            JOptionPane.showMessageDialog(jPanel1, "Enter Characters only !","Error",JOptionPane.ERROR_MESSAGE);
            evt.consume();
        }
        
    }//GEN-LAST:event_publisherKeyTyped

    private void editionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editionKeyTyped
        
         if(Character.isLetter(evt.getKeyChar()) && Character.isDigit(evt.getKeyChar()) && !(evt.getKeyChar() == KeyEvent.VK_ENTER)){
            JOptionPane.showMessageDialog(jPanel1, "Enter Characters and Digits e.g ' 5th '","Error",JOptionPane.ERROR_MESSAGE);
            evt.consume();
        }
        
    }//GEN-LAST:event_editionKeyTyped

    private void invoiceNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_invoiceNoKeyTyped
       
        if(Character.isLetter(evt.getKeyChar()) && !(evt.getKeyChar() == KeyEvent.VK_ENTER)){
            JOptionPane.showMessageDialog(jPanel1, "Enter Digits only !","Error",JOptionPane.ERROR_MESSAGE);
            evt.consume();
        }
        
    }//GEN-LAST:event_invoiceNoKeyTyped

    private void bookIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bookIdKeyPressed
        
        if(evt.getKeyChar() == KeyEvent.VK_ENTER)
           bookTitle.requestFocus();
       
    }//GEN-LAST:event_bookIdKeyPressed

    private void bookTitleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bookTitleKeyPressed
       
         if(evt.getKeyChar() == KeyEvent.VK_ENTER)
            authorName.requestFocus();
        
    }//GEN-LAST:event_bookTitleKeyPressed

    private void authorNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_authorNameKeyPressed
        
         if(evt.getKeyChar() == KeyEvent.VK_ENTER)
            publisher.requestFocus();
        
    }//GEN-LAST:event_authorNameKeyPressed

    private void publisherKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_publisherKeyPressed
        
         if(evt.getKeyChar() == KeyEvent.VK_ENTER)
            edition.requestFocus();
        
    }//GEN-LAST:event_publisherKeyPressed

    private void editionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editionKeyPressed
       
         if(evt.getKeyChar() == KeyEvent.VK_ENTER)
            invoiceNo.requestFocus();
        
    }//GEN-LAST:event_editionKeyPressed

    private void invoiceNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_invoiceNoKeyPressed
        
         if(evt.getKeyChar() == KeyEvent.VK_ENTER)
            invoiceDate.requestFocus();
        
    }//GEN-LAST:event_invoiceNoKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibraryForm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibraryForm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibraryForm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibraryForm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibraryForm2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField authorName;
    private javax.swing.JTextField bookId;
    private javax.swing.JTextField bookTitle;
    private javax.swing.JTextField edition;
    private com.toedter.calendar.JDateChooser invoiceDate;
    private javax.swing.JTextField invoiceNo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField publisher;
    // End of variables declaration//GEN-END:variables
}
