/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaproject;

import com.sun.glass.events.KeyEvent;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import loginpanel.AdminsForm;
import loginpanel2.payroll;


/**
 *
 * @author amonkats
 */
public class PayRollForm extends javax.swing.JFrame {
    
    final double WEIGHTING = 5000;
    final double BASIC_SALARY_FULLTIME = 250000000;
    final double BASIC_SALARY_PARTTIME = 2000000;
    
    final double CHANCELLOR = 7000000;
    final double CLEANER = 200000;
    final double LIBRARIAN = 700000;
    final double RECEPTIONIST = 660000;
    final double ICT_MANAGER = 1500000;
    final double DEAN = 500000;
    final double OTHERS = 1200000;

    /**
     * Creates new form PayRollForm
     */
    public PayRollForm() {
        initComponents();
        setResizable(false);
        setTitle("IUEA Database Oriented System");
       
    }
    
     public class Search{
    
        Connection conn = null;
        PreparedStatement pst = null;
        ResultSet rs = null;
        
     public ResultSet find(String str){
            try{
                conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/javaproject", "root", "");
                String query = "select * from employee where Employee_Name = ?";
                pst = conn.prepareStatement(query);
                pst.setString(1, str);
                rs = pst.executeQuery();
            }catch(Exception ex){
                JOptionPane.showMessageDialog(null, "Connection Failed !");
            }
            return rs;
        }
     
     public ResultSet find2(String str){
            try{
                conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/javaproject", "root", "");
                String query = "select * from employee2 where Employee_Name = ?";
                pst = conn.prepareStatement(query);
                pst.setString(1, str);
                rs = pst.executeQuery();
            }catch(Exception ex){
                JOptionPane.showMessageDialog(null, "Connection Failed !");
            }
            return rs;
        }
    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ref = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        addr = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        pay = new javax.swing.JTextField();
        emp2 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        emp = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        faculty = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtbasic = new javax.swing.JTextField();
        txtweight = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        schedule = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        jobTitle = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        deduc = new javax.swing.JTextField();
        gross = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        netpay = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        txtpension = new javax.swing.JTextField();
        txttax = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtstudent = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        wages = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jLabel14.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel14.setText("Schedule");

        jLabel15.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel15.setText("Job Type");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(730, 320));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel1.setText("IUEA PAY ROLL MANAGEMENT SYSTEM");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 460, 30));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "To be filled by other Employees", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 12))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel2.setText("Reference No.");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 84, 25));

        ref.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                emp2KeyPressed(evt);
            }
        });
        jPanel2.add(ref, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 85, 158, 30));

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel3.setText("Address");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 55, 80, 20));

        addr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                emp2KeyPressed(evt);
            }
        });
        jPanel2.add(addr, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 158, 30));

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel4.setText("Employee Name");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 90, 20));
        jPanel2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 91, 158, 25));

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel5.setText("Payment Card No.");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, 25));
        jPanel2.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 135, 158, 25));

        pay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                emp2KeyPressed(evt);
            }
        });
        jPanel2.add(pay, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 125, 158, 30));

        emp2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                emp2KeyPressed(evt);
            }
        });
        jPanel2.add(emp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 158, 25));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 380, 170));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "To be filled by Lecturers Only", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 12))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel6.setText("Employee Name");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 19, 90, 20));

        emp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                empKeyPressed(evt);
            }
        });
        jPanel3.add(emp, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 158, 30));

        jLabel7.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel7.setText("Address");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 74, 25));

        address.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                empKeyPressed(evt);
            }
        });
        jPanel3.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 158, 30));

        jLabel8.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel8.setText("Faculty");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 74, 20));

        faculty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                empKeyPressed(evt);
            }
        });
        jPanel3.add(faculty, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 158, 30));

        jLabel9.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel9.setText("Lecturer ID");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 74, 25));

        id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                empKeyPressed(evt);
            }
        });
        jPanel3.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 135, 158, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 350, 170));

        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jLabel12.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel12.setText("Basic Salary");

        txtbasic.setEditable(false);
        txtbasic.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtbasic.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtweight.setEditable(false);
        txtweight.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtweight.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel13.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel13.setText("IUEA weighting");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtweight, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtbasic, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtweight, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtbasic)
                        .addContainerGap())))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 350, 100));

        jPanel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel16.setText("Schedule");
        jPanel8.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 440, 94, 24));

        jLabel17.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel17.setText("Shedule");
        jPanel8.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 80, 24));

        schedule.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one...", "Full time", "Part time" }));
        schedule.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jobTitleItemStateChanged(evt);
            }
        });
        jPanel8.add(schedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 140, 30));

        jLabel28.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel28.setText("Job Title");
        jPanel8.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 14, 94, 24));

        jobTitle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one...", "Lecturer", "Cleaner", "Vice Chancellor", "Librarian", "Receptionist", "ICT Manager", "Dean of students", "Other Admins" }));
        jobTitle.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jobTitleItemStateChanged(evt);
            }
        });
        jPanel8.add(jobTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 140, 30));

        jLabel29.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel29.setText("*Lecturers only");
        jPanel8.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 100, -1));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 380, 100));

        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel18.setText("Pension");
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 440, 94, 24));

        deduc.setEditable(false);
        deduc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        deduc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel6.add(deduc, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 158, 30));

        gross.setEditable(false);
        gross.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        gross.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel6.add(gross, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 158, 30));

        jLabel19.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel19.setText("Net Pay");
        jPanel6.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 60, 24));

        jLabel22.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel22.setText("Student Loan");
        jPanel6.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 440, 94, 24));

        netpay.setEditable(false);
        netpay.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        netpay.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel6.add(netpay, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 158, 30));

        jLabel23.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel23.setText("Gross Pay");
        jPanel6.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 70, 24));

        jLabel24.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel24.setText("Deductions");
        jPanel6.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 70, 24));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, 380, 140));

        jPanel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel20.setText("Pension");
        jPanel9.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 440, 94, 24));

        txtpension.setEditable(false);
        txtpension.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtpension.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel9.add(txtpension, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 158, 30));

        txttax.setEditable(false);
        txttax.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txttax.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel9.add(txttax, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 158, 30));

        jLabel21.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel21.setText("Student Loan");
        jPanel9.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 80, 24));

        jLabel25.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel25.setText("Student Loan");
        jPanel9.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 440, 94, 24));

        txtstudent.setEditable(false);
        txtstudent.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtstudent.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtstudent.setText("UGX. 800000 ");
        jPanel9.add(txtstudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 95, 158, 30));

        jLabel26.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel26.setText("Tax");
        jPanel9.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 24));

        jLabel27.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel27.setText("Pension");
        jPanel9.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 70, 24));

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel10.setText("* reserved");
        jPanel9.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 70, 20));

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 350, 140));

        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        wages.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        wages.setText("View Wages");
        wages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wagesActionPerformed(evt);
            }
        });
        jPanel4.add(wages, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 110, 40));

        jButton3.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 110, 40));

        jButton4.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 110, 40));

        jButton1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 110, 40));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 90, 150, 420));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void wagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wagesActionPerformed

        ResultSet rs = null;
        ResultSet rs2 = null;
        Search s = new Search();
        rs = s.find(emp.getText());
        rs2 = s.find2(emp2.getText());
        try {
            if(evt.getSource() == wages && !rs.isBeforeFirst() && !rs2.isBeforeFirst()){
                JOptionPane.showMessageDialog(null, "No Employee Info for '" + emp.getText() + emp2.getText()+ "' ", "Error",JOptionPane.ERROR_MESSAGE);
                txtweight.setText("");
                txtbasic.setText("");
            }
            else{
            
             if(!rs.isBeforeFirst() && jobTitle.getSelectedItem().equals("Lecturer") && schedule.getSelectedItem().equals("Full time")){
                JOptionPane.showMessageDialog(null, "You are not a lecturer !","Eror",JOptionPane.ERROR_MESSAGE);
            }
            
           else if(!rs.isBeforeFirst() && jobTitle.getSelectedItem().equals("Lecturer") && schedule.getSelectedItem().equals("Part time")){
                JOptionPane.showMessageDialog(null, "You are not a lecturer !","Eror",JOptionPane.ERROR_MESSAGE);
           } 
             
           else if(rs.isBeforeFirst() && !(jobTitle.getSelectedItem().equals("Lecturer"))){
                JOptionPane.showMessageDialog(null, "Access Denied !","Eror",JOptionPane.ERROR_MESSAGE);
                txtbasic.setText("");
                txtpension.setText("");
                txtweight.setText("");
                txttax.setText("");
        
                gross.setText("");
                deduc.setText("");
                netpay.setText("");
       
                jobTitle.setSelectedItem("Select one...");
                schedule.setSelectedItem("Select one...");
           }  
            }
    
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(null, "Error");
        }
   
       double enterWeight = Double.parseDouble(txtweight.getText());
       double enterBasic = Double.parseDouble(txtbasic.getText());
       double Gross = enterWeight + enterBasic;
       String result = String.format("%.2f", Gross);
       gross.setText(result);
       gross.setText("UGX. " + result);
       
       double tax = 0.09 * Gross;
       String result2 = String.format("%.2f", tax);
       txttax.setText(result2);
       txttax.setText("UGX. " + result2);
       
       double deductions = Gross - tax;
       String result3 = String.format("%.2f", deductions);
       deduc.setText(result3);
       deduc.setText("UGX. " + result3);
       
       double pension = deductions * 0.12;
       String result4 = String.format("%.2f", pension);
       txtpension.setText(result4);
       txtpension.setText("UGX. " + result4);
       
       double totalDeductions = tax + pension;
       double netPay = Gross - totalDeductions;
       String result5 = String.format("%.2f", netPay);
       netpay.setText(result5);
       netpay.setText("UGX. " + result5);

        
    }//GEN-LAST:event_wagesActionPerformed

    private void jobTitleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jobTitleItemStateChanged
        
        ResultSet rs = null;
        Search s = new Search();
        rs = s.find(emp.getText());
        
        try {
               if(rs.isBeforeFirst() && jobTitle.getSelectedItem().equals("Lecturer") && schedule.getSelectedItem().equals("Full time")){
                String result = String.format("%.2f", BASIC_SALARY_FULLTIME);
                String result2 = String.format("%.2f", WEIGHTING);
                txtweight.setText(result2);
                txtbasic.setText(result);
            }
            
            else if(rs.isBeforeFirst() && jobTitle.getSelectedItem().equals("Lecturer") && schedule.getSelectedItem().equals("Part time")){
                String result = String.format("%.2f", BASIC_SALARY_PARTTIME);
                String result2 = String.format("%.2f", WEIGHTING);
                txtweight.setText(result2);
                txtbasic.setText(result);
            }
            
            else if(jobTitle.getSelectedItem().equals("Lecturer")){
                JOptionPane.showMessageDialog(null, "Check your schedule !");
            }
           
 
            else{
                
             if(jobTitle.getSelectedItem().equals("Cleaner")){
                String result = String.format("%.2f", CLEANER);
                String result2 = String.format("%.2f", WEIGHTING);
                txtweight.setText(result2);
                txtbasic.setText(result);
            }
            
            else if(jobTitle.getSelectedItem().equals("Vice Chancellor")){
                String result = String.format("%.2f", CHANCELLOR);
                String result2 = String.format("%.2f", WEIGHTING);
                txtweight.setText(result2);
                txtbasic.setText(result);
            }
            
            else if(jobTitle.getSelectedItem().equals("Librarian")){
                String result = String.format("%.2f", LIBRARIAN);
                String result2 = String.format("%.2f", WEIGHTING);
                txtweight.setText(result2);
                txtbasic.setText(result);
            }
            
            else if(jobTitle.getSelectedItem().equals("ICT Manager")){
                String result = String.format("%.2f", ICT_MANAGER);
                String result2 = String.format("%.2f", WEIGHTING);
                txtweight.setText(result2);
                txtbasic.setText(result);
            }
            
            else if(jobTitle.getSelectedItem().equals("Receptionist")){
                String result = String.format("%.2f", RECEPTIONIST);
                String result2 = String.format("%.2f", WEIGHTING);
                txtweight.setText(result2);
                txtbasic.setText(result);
            }
            
            else if(jobTitle.getSelectedItem().equals("Dean of students")){
                String result = String.format("%.2f", DEAN);
                String result2 = String.format("%.2f", WEIGHTING);
                txtweight.setText(result2);
                txtbasic.setText(result);
            }
            
            else if(jobTitle.getSelectedItem().equals("Other Admins")){
                String result = String.format("%.2f", OTHERS);
                String result2 = String.format("%.2f", WEIGHTING);
                txtweight.setText(result2);
                txtbasic.setText(result);
            }
           
            }
        } catch (SQLException ex) {
            
        }
         
    }//GEN-LAST:event_jobTitleItemStateChanged

    private void empKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_empKeyPressed
       
        ResultSet rs = null;
        Search s = new Search();
        rs = s.find(emp.getText());
        
        try {
            
            if(!rs.isBeforeFirst() && evt.getKeyCode() == KeyEvent.VK_ENTER){
                JOptionPane.showMessageDialog(null, "Not an employee at IUEA !", "Error",JOptionPane.ERROR_MESSAGE);
                address.setText("");
                faculty.setText("");
                id.setText("");
                
            }
            
            else{
                if(rs.next()){
                
              if(evt.getKeyCode() == KeyEvent.VK_ENTER){
                emp.setText(rs.getString("Employee_Name"));
                address.setText(rs.getString("Address"));
                faculty.setText(rs.getString("Faculty"));
                id.setText(rs.getString("Lecturer_ID"));
            }
    
            }
       }
           
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(null, "Connection Failed !");
        }
        
        
    }//GEN-LAST:event_empKeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        emp.setText("");
        address.setText("");
        id.setText("");
        faculty.setText("");
        
        emp2.setText("");
        addr.setText("");
        ref.setText("");
        pay.setText("");
        
        txtbasic.setText("");
        txtpension.setText("");
        txtweight.setText("");
        txttax.setText("");
        
        gross.setText("");
        deduc.setText("");
        netpay.setText("");
       
        jobTitle.setSelectedItem("Select one...");
        schedule.setSelectedItem("Select one...");
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void emp2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emp2KeyPressed
        
        ResultSet rs = null;
        Search s = new Search();
        rs = s.find2(emp2.getText());
        
        try {
            
             if(!rs.isBeforeFirst() && evt.getKeyCode() == KeyEvent.VK_ENTER){
                JOptionPane.showMessageDialog(null, "Not an employee at IUEA !", "Error",JOptionPane.ERROR_MESSAGE);
                addr.setText("");
                ref.setText("");
                pay.setText("");
            }
             
             else{
            
            if(rs.next()){
              if(evt.getKeyCode() == KeyEvent.VK_ENTER){
                emp2.setText(rs.getString("Employee_Name"));
                addr.setText(rs.getString("Address"));
                ref.setText(rs.getString("ReferenceNo"));
                pay.setText(rs.getString("Payment_CardNo"));
                }
            }
        }
                      
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(null, "Connection Failed !");
        }
        
        
    }//GEN-LAST:event_emp2KeyPressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        new payroll().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PayRollForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PayRollForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PayRollForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PayRollForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PayRollForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addr;
    private javax.swing.JTextField address;
    private javax.swing.JTextField deduc;
    private javax.swing.JTextField emp;
    private javax.swing.JTextField emp2;
    private javax.swing.JTextField faculty;
    private javax.swing.JTextField gross;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JComboBox<String> jobTitle;
    private javax.swing.JTextField netpay;
    private javax.swing.JTextField pay;
    private javax.swing.JTextField ref;
    private javax.swing.JComboBox<String> schedule;
    private javax.swing.JTextField txtbasic;
    private javax.swing.JTextField txtpension;
    private javax.swing.JTextField txtstudent;
    private javax.swing.JTextField txttax;
    private javax.swing.JTextField txtweight;
    private javax.swing.JButton wages;
    // End of variables declaration//GEN-END:variables
}
