/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaproject;
import java.awt.*;
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.*;
import loginpanel2.RegAdminLogin;
import java.io.*;

import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author amonkats
 */
public class RegForm extends javax.swing.JFrame {

    String str;
    
    
    public RegForm() {
        initComponents();
        setLocation(50,40);
        setResizable(false);
        setTitle("IUEA Database Oriented System");
       
    }
    
     public class Search{
    
        Connection conn = null;
        PreparedStatement pst = null;
        ResultSet rs = null;
        
     public ResultSet find(String str){
            try{
                conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/javaproject", "root", "");
                String query = "select * from register where RegNo = ?";
                pst = conn.prepareStatement(query);
                pst.setString(1, str);
                rs = pst.executeQuery();
               
            }catch(Exception ex){
                JOptionPane.showMessageDialog(null, "Connection Failed !");
            }
            return rs;
        }
    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        reg = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        regNo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        lname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        prog = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        courseCode = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jCmbYear = new javax.swing.JComboBox<>();
        jCmbIntake = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jCmbFaculty = new javax.swing.JComboBox<>();
        address = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        back = new javax.swing.JButton();
        photo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        dob = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(672, 458));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\amonkats\\Documents\\NetBeansProjects\\JavaProject\\src\\javaproject\\pics\\Logo_sized.png")); // NOI18N

        jLabel9.setFont(new java.awt.Font("Old English Text MT", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 51, 51));
        jLabel9.setText("   International University Of East Africa");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 18, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Search here (RegNo): ");

        reg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                regKeyPressed(evt);
            }
        });

        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(reg, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reg)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                        .addGap(3, 3, 3)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(21, 21, 21))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 106, 590, 60));

        regNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                regNoKeyPressed(evt);
            }
        });
        jPanel1.add(regNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 130, 31));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Reg No.");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 180, 80, 23));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("First Name");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 223, 108, 23));

        fname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fnameKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fnameKeyTyped(evt);
            }
        });
        jPanel1.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 130, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Last Name");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 261, 85, 23));

        lname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lnameKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lnameKeyTyped(evt);
            }
        });
        jPanel1.add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 130, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Programme");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 302, 90, 23));

        prog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                progActionPerformed(evt);
            }
        });
        prog.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                progKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                progKeyTyped(evt);
            }
        });
        jPanel1.add(prog, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 130, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Date of Birth");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 108, 27));

        phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneActionPerformed(evt);
            }
        });
        phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                phoneKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phoneKeyTyped(evt);
            }
        });
        jPanel1.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 130, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("Mobile Phone");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 381, 83, 23));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Course Code");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 180, 84, 23));
        jPanel1.add(courseCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 177, 160, 31));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Year");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 84, 23));

        jCmbYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select year..", "2011", "2012", "2013", "2014", "2015", "2016" }));
        jPanel1.add(jCmbYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 216, 160, 40));

        jCmbIntake.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select Intake..", "JANUARY INTAKE", "AUGUST INTAKE" }));
        jPanel1.add(jCmbIntake, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, 160, 40));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Intake");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 84, 23));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Faculty");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 73, 23));

        jCmbFaculty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "choose one..", "SCIENCE AND TECHNOLOGY", "ENGINEERING", "BUSINESS " }));
        jCmbFaculty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jCmbFacultyKeyPressed(evt);
            }
        });
        jPanel1.add(jCmbFaculty, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, 160, 40));

        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });
        address.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                addressKeyTyped(evt);
            }
        });
        jPanel1.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 377, 160, 30));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("Address");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 380, 78, 23));

        jButton4.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jButton4.setText(" Register Student");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 430, 150, 32));

        jButton7.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jButton7.setText("Clear");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 430, 120, 32));

        jButton2.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 110, 32));

        back.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 130, 32));

        photo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(photo, new org.netbeans.lib.awtextra.AbsoluteConstraints(714, 164, 170, 180));

        jButton1.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jButton1.setText("Upload photo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(753, 363, 110, 40));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(724, 20, 150, 80));

        dob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobActionPerformed(evt);
            }
        });
        dob.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dobKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dobKeyTyped(evt);
            }
        });
        jPanel1.add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 130, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 909, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        ResultSet rs = null;
        Search s = new Search();
        rs = s.find(reg.getText());
        
        try {
            if(!rs.isBeforeFirst()){
                JOptionPane.showMessageDialog(null, "Continue to register a student");
                reg.requestFocus();
            }
        } catch (SQLException ex) {
            
        }

        try {
            if(rs.next()){
                regNo.setText(rs.getString("RegNo"));
                fname.setText(rs.getString("First_Name"));
                lname.setText(rs.getString("Last_Name"));
                prog.setText(rs.getString("Programme"));
                dob.setText(rs.getString("DOB"));
                phone.setText(rs.getString("Mobile_Phone"));
                courseCode.setText(rs.getString("Course_Code"));
                jCmbYear.setSelectedItem(rs.getString("Year_Joined"));
                jCmbIntake.setSelectedItem(rs.getString("Intake"));
                jCmbFaculty.setSelectedItem(rs.getString("Faculty_Name"));
                address.setText(rs.getString("Address"));
                
                //Setting an image to its jlabel from the database
                Blob blob = rs.getBlob("MyImage");
                byte[] content = blob.getBytes(1L, (int)blob.length());
                ImageIcon iIcon = new ImageIcon(content);
                Image img = iIcon.getImage();
                Image newImage = img.getScaledInstance(photo.getWidth(), photo.getHeight(), Image.SCALE_SMOOTH);
                iIcon = new ImageIcon(newImage);
                photo.setIcon(iIcon);
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Connection Failed !");
        } 

        if(evt.getSource().equals(btnSearch) && reg.getText().length()==0){
            lname.setText("");
            prog.setText("");
            jCmbYear.setSelectedItem("select year..");
            JOptionPane.showMessageDialog(null, "Otherwise nothing to search !", "Error",JOptionPane.ERROR_MESSAGE);
        }
        

    }//GEN-LAST:event_btnSearchActionPerformed

    private void progActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_progActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_progActionPerformed

    private void phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneActionPerformed

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        Connection conn = null;
        PreparedStatement pst = null;
        ResultSet rs = null;
        
        if(reg.getText().equals("") && regNo.getText().equals("") && fname.getText().equals("")
            && lname.getText().equals("") && prog.getText().equals("") && dob.getText().equals("")
            && phone.getText().equals("") && courseCode.getText().equals("")
            && address.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Nothing to register !", "Error",JOptionPane.ERROR_MESSAGE);
            reg.requestFocus();
        }

        else if(regNo.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Fill in RegNo !", "Error",JOptionPane.ERROR_MESSAGE);
            regNo.requestFocus();
        }

        else if(fname.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Fill in First Name !", "Error",JOptionPane.ERROR_MESSAGE);
            fname.requestFocus();
        }

        else if(lname.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Fill in Last Name !", "Error",JOptionPane.ERROR_MESSAGE);
            lname.requestFocus();
        }

        else if(prog.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Fill in Programme !", "Error",JOptionPane.ERROR_MESSAGE);
            prog.requestFocus();
        }

        else if(dob.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Fill in DOB !", "Error",JOptionPane.ERROR_MESSAGE);
            dob.requestFocus();
        }

        else if(phone.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Fill in Phone Contact !", "Error",JOptionPane.ERROR_MESSAGE);
            phone.requestFocus();
        }

        else if(courseCode.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Fill in Course Code !", "Error",JOptionPane.ERROR_MESSAGE);
            courseCode.requestFocus();
        }

        else if(jCmbYear.getSelectedItem().equals("Year_Joined")){
            JOptionPane.showMessageDialog(null, "select Year !", "Error",JOptionPane.ERROR_MESSAGE);
            jCmbYear.requestFocus();
        }

        else if(jCmbIntake.getSelectedItem().equals("Intake")){
            JOptionPane.showMessageDialog(null, "Select Intake !", "Error",JOptionPane.ERROR_MESSAGE);
            jCmbIntake.requestFocus();
        }

        else if(jCmbFaculty.getSelectedItem().equals("Faculty_Name")){
            JOptionPane.showMessageDialog(null, "Select Faculty !", "Error",JOptionPane.ERROR_MESSAGE);
            jCmbFaculty.requestFocus();
        }

        else if(address.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Fill in Address !", "Error",JOptionPane.ERROR_MESSAGE);
            address.requestFocus();
        }
        
        
        else if(photo.getIcon()==null)
            JOptionPane.showMessageDialog(null, "Upload an Image !", "Error",JOptionPane.ERROR_MESSAGE);

        else {

            try {
                conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/javaproject", "root", "");
                String query = "Insert into register values(?,?,?,?,?,?,?,?,?,?,?,?)";
                pst = conn.prepareStatement(query);
                InputStream is = new FileInputStream(new File(str));
                
                pst.setString(1, regNo.getText());
                pst.setString(2, fname.getText());
                pst.setString(3, lname.getText());
                pst.setString(4, prog.getText());
                pst.setString(5, dob.getText());
                pst.setString(6, phone.getText());
                pst.setString(7, courseCode.getText());
                pst.setInt(8, Integer.parseInt(jCmbYear.getSelectedItem().toString()));
                pst.setString(9, jCmbIntake.getSelectedItem().toString());
                pst.setString(10, jCmbFaculty.getSelectedItem().toString());
                pst.setString(11, address.getText());
                pst.setBlob(12, is);

                int count = pst.executeUpdate();
                if(count > 0)
                    JOptionPane.showMessageDialog(null, "Data inserted, student registered");
                else
                    JOptionPane.showMessageDialog(null, "Data exists");
                pst.close();
                conn.close();
                is.close();
            } catch (SQLException ex) {
                 JOptionPane.showMessageDialog(null, ex);
            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(null, ex);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
         
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        reg.setText("");
        regNo.setText("");
        fname.setText("");
        lname.setText("");
        prog.setText("");
        dob.setText("");
        phone.setText("");
        courseCode.setText("");
        jCmbYear.setSelectedItem("select year..");
        jCmbIntake.setSelectedItem("select Intake..");
        jCmbFaculty.setSelectedItem("choose one..");
        address.setText("");
        photo.setIcon(null);

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        dispose();
        new RegAdminLogin().setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void regKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_regKeyPressed
        
        if(evt.getKeyChar() == KeyEvent.VK_ENTER)
            regNo.requestFocus();
        
    }//GEN-LAST:event_regKeyPressed

    private void regNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_regNoKeyPressed
        
        if(evt.getKeyChar() == KeyEvent.VK_ENTER)
            fname.requestFocus();
        
    }//GEN-LAST:event_regNoKeyPressed

    private void fnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fnameKeyPressed
        
        if(evt.getKeyChar() == KeyEvent.VK_ENTER)
            lname.requestFocus();
        
    }//GEN-LAST:event_fnameKeyPressed

    private void lnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lnameKeyPressed
        
        if(evt.getKeyChar() == KeyEvent.VK_ENTER)
            prog.requestFocus();
        
    }//GEN-LAST:event_lnameKeyPressed

    private void progKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_progKeyPressed
        
        if(evt.getKeyChar() == KeyEvent.VK_ENTER)
            dob.requestFocus();
        
    }//GEN-LAST:event_progKeyPressed

    private void phoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneKeyPressed
        
        if(evt.getKeyChar() == KeyEvent.VK_ENTER)
            courseCode.requestFocus();
        
    }//GEN-LAST:event_phoneKeyPressed

    private void jCmbFacultyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCmbFacultyKeyPressed
        
        if(evt.getKeyChar() == KeyEvent.VK_ENTER)
            address.requestFocus();
        
    }//GEN-LAST:event_jCmbFacultyKeyPressed

    private void fnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fnameKeyTyped
        
         if(Character.isDigit(evt.getKeyChar()) && !(evt.getKeyChar() == com.sun.glass.events.KeyEvent.VK_ENTER)){
            JOptionPane.showMessageDialog(jPanel1, "Enter Characters only !","Error",JOptionPane.ERROR_MESSAGE);
            evt.consume();
        }
        
        
    }//GEN-LAST:event_fnameKeyTyped

    private void lnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lnameKeyTyped
        
         if(Character.isDigit(evt.getKeyChar()) && !(evt.getKeyChar() == com.sun.glass.events.KeyEvent.VK_ENTER)){
            JOptionPane.showMessageDialog(jPanel1, "Enter Characters only !","Error",JOptionPane.ERROR_MESSAGE);
            evt.consume();
        }
        
        
    }//GEN-LAST:event_lnameKeyTyped

    private void progKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_progKeyTyped
        
         if(Character.isDigit(evt.getKeyChar()) && !(evt.getKeyChar() == KeyEvent.VK_ENTER)){
            JOptionPane.showMessageDialog(jPanel1, "Enter Characters only !","Error",JOptionPane.ERROR_MESSAGE);
            evt.consume();
        }
        
        
    }//GEN-LAST:event_progKeyTyped

    private void addressKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addressKeyTyped
        
         if(Character.isDigit(evt.getKeyChar()) && !(evt.getKeyChar() == KeyEvent.VK_ENTER)){
            JOptionPane.showMessageDialog(jPanel1, "Enter Characters only !","Error",JOptionPane.ERROR_MESSAGE);
            evt.consume();
        }
        
        
    }//GEN-LAST:event_addressKeyTyped

    private void phoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneKeyTyped
        
         if(Character.isLetter(evt.getKeyChar()) && !(evt.getKeyChar() == KeyEvent.VK_ENTER)){
            JOptionPane.showMessageDialog(jPanel1, "Enter Digits only !","Error",JOptionPane.ERROR_MESSAGE);
            evt.consume();
        }
        
    }//GEN-LAST:event_phoneKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        JFileChooser fc = new JFileChooser();
        fc.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Image", "jpg", "gif", "png");
        fc.addChoosableFileFilter(filter);
        
        int result = fc.showSaveDialog(null);
        if(result == JFileChooser.APPROVE_OPTION){
            File fileSelected = fc.getSelectedFile();
            String path = fileSelected.getAbsolutePath();
            //str = path;
            photo.setIcon(resizeImage(path));
        }
        else if (result == JFileChooser.CANCEL_OPTION)
            JOptionPane.showMessageDialog(null, "File not Selected !","Error",JOptionPane.ERROR_MESSAGE);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void dobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dobActionPerformed

    private void dobKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dobKeyPressed
        
         if(evt.getKeyChar() == KeyEvent.VK_ENTER)
            phone.requestFocus();
        
    }//GEN-LAST:event_dobKeyPressed

    private void dobKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dobKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_dobKeyTyped

    public ImageIcon resizeImage(String imagePath){
        
        ImageIcon myImage = new ImageIcon(imagePath);
        Image img = myImage.getImage();
        Image newImage = img.getScaledInstance(photo.getWidth(), photo.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImage);
        return image;
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JButton back;
    private javax.swing.JButton btnSearch;
    private javax.swing.JTextField courseCode;
    private javax.swing.JTextField dob;
    private javax.swing.JTextField fname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jCmbFaculty;
    private javax.swing.JComboBox<String> jCmbIntake;
    private javax.swing.JComboBox<String> jCmbYear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField lname;
    private javax.swing.JTextField phone;
    private javax.swing.JLabel photo;
    private javax.swing.JTextField prog;
    private javax.swing.JTextField reg;
    private javax.swing.JTextField regNo;
    // End of variables declaration//GEN-END:variables
}
