/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tables;

import java.awt.Font;
import loginpanel2.StudentsAccountLogin;
import java.sql.*;
import net.proteanit.sql.DbUtils;
import javax.swing.*;

/**
 *
 * @author amonkats
 */
public class PersonalAccountTable extends javax.swing.JFrame {

    /**
     * Creates new form PersonalAccountTable
     */
    public PersonalAccountTable() {
        initComponents();
        setResizable(false);
        setTitle("IUEA Database Oriented System");
        setLocation(110, 95);
    }

    public PersonalAccountTable(ResultSet rs) {
        initComponents();
        table.setModel(DbUtils.resultSetToTableModel(rs));
        table.setRowHeight(40);
        setResizable(false);
        setLocation(110, 95);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RegNo", "Names", "Function Fee", "Tuition Fee"
            }
        ));
        jScrollPane1.setViewportView(table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 590, 230));

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel1.setText("IUEA PERSONAL STUDENT'S ACCOUNT");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 390, 30));

        jButton1.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jButton1.setText("Issue Ledger");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, 120, 30));

        jButton2.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 120, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 726, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        dispose();
        new StudentsAccountLogin().setVisible(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        String header;
        int selectedRow = table.getSelectedRow();
        
        if(selectedRow < 0)
            JOptionPane.showMessageDialog(null, "No row Selected !", "Error",JOptionPane.ERROR_MESSAGE);
        
        else{
        String setToTextArea = new String();
        int setToTextArea2 = 0;
        int setToTextArea3 = 0;
        int finalFee = 1950000;
        int total2 = 0;
        
        for(int i = 0; i < table.getColumnCount(); i++){
            setToTextArea = (String) table.getValueAt(selectedRow, 1);
            setToTextArea2 = (int) table.getValueAt(selectedRow, 2);
            setToTextArea3 = (int) table.getValueAt(selectedRow, 3);
            total2 = setToTextArea3 - finalFee;
        }
       
       
        header = "\t               " + "    " + "International University of East Africa 2016-2017 - (From 1-Jul-2016)"
                +"\n" + "\t" + "\t" + "\t" + "P.O Box 35502, Kampala" + "\n" + "\t" + "\t" + "\t" + "               Uganda" +"\n"
                +"\n" +"\n" + "\t" + "\t" + "\t" + "        " +setToTextArea + "\n" + "\t" + "\t" + "\t" + "        Ledger Account"
                + "\n" + "\n" + "\t" + "\t" + "\t" + "1-Jul-2016 to 14-Sep-2016" + "\n" 
                + "_________________________________________________________________________________________________" + "\n"
                + "   " + "Date" + "\t " + "Particulars" + "\t" + "\t" + "Vch Type" + "\t" + "Vch No./Excise Inv.No."+ "\t   " + "     " + "Debit" + "\t" + "  " + "Credit" + "\n"
                + "_________________________________________________________________________________________________" + "\n"
                + "1-7-2016" + " " + "    By" +" " + "   Opening Balance" + "\t" + "       " + "\t" + "\t" + "   " + "\t" +"\t" +"  " + "600.00" + "\n" + "\n"
                + "19-8-2016" + " " + "  By" +"   " + " Dfcu Collection Ugx" + "\t" + "Bank Reciept" + "\t" + "\t" + "804" + "\t" +"     " + total2 + "\t" + "  "+ setToTextArea3
                + "" + " " + "     " +"\n" + "\t" + "  Fees Payment" + "\t" + "       " + "\t" + "\t" + "   " + "\n" + "\n"
                + "22-8-2016" + " " + "  To" +" " + "  Undergraduate Fees" + "\t" + "Journal" + "\t" + "\t" + "894"
                + "\t" + "      " + setToTextArea3 + "\n" + "\t" +"" + "  Fees yr.2.1 BIT AUG 15" + "\t" + "\t" + "\t" + "            " +  "_____________________________" + "\n"
                + "\t" + "\t" + "\t" +"\t" +"\t" +"\t" +"      " + setToTextArea3 + "\t" +"  " + setToTextArea3 + "\n" + "\n" + "\t" + "By" + "     " + "Closing Balance" + "\t" + "\t" + "\t" +"           "
                + "______________________________" + "\n" + "\t" + "\t" + "\t" + "\t" +"\t" +"\t" +"      " + setToTextArea3 + " \t" + "  " + setToTextArea3 + "\n" + "\t" + "\t" + "\t" + "\t" +"\t" +"           "
                + "______________________________";
        dispose();
        new PrintLedger(header).setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonalAccountTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonalAccountTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonalAccountTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonalAccountTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PersonalAccountTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
